### PR TITLE
composer: add missing dependency for doctrine/doctrine-fixtures-bundle

### PR DESCRIPTION
**Pull request by vpassama**
used in sam:database:reset function

The bundle should declare doctrine-fixtures as a dependency in its composer.json.

### CODE REVIEW

**Comment by vpassama** [comment]
After a short discussion on this subject with @datanel, this PR needs a review about doctrine versions involved..

Also, this dependency may be declared in the required-dev section of composer as fixtures shouldn't be used in prod environement.

**Comment by datanel** [comment]
The version is good.
If you have a dependency in a "require-dev" of a dependency, I don't think composer will install it.
You need to put it in the require-dev of the global composer.json. Not sure

**Comment by vpassama** [comment]
I think it will install it but I will try before. If we do this, I'll add a check in the command in order to launch fixtures only if we're in dev environement.

**Comment by datanel** [comment]
http://stackoverflow.com/a/21171171

**Comment by vpassama** [comment]
I realize the user should be warned if he forgot to declare the doctrine-fixtures-bundle in the require-dev section of his global composer.
Maybe I should throw an exception if doctrine-fixtures-bundle isn't found instead of doing nothing.

@datanel ?

**Comment by datanel** [comment]
> Maybe I should throw an exception
How do you plan to do that?

**Comment by vpassama** [comment]
@datanel, I did this, tell me if it's ok for you.

**Comment by datanel** [comment]
ok I merge like that it doesn't matter if it is require-dev or suggest in this case.

**Pull request merged**
